<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data analysis with python - 3&nbsp; Basic visualization tools</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../code/3_advanced_vis_tools.html" rel="next">
<link href="../code/1_intro.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic visualization tools</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../" class="sidebar-logo-link">
      <img src="../images/tree_of_life.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Data analysis with python</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data analysis with Python</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/1_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction into data vis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/2_basic_vis_tools.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic visualization tools</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/3_advanced_vis_tools.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Advanced visualization tools</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/4_dashbords.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Creating Dashbords with Plotly and Dash</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#notebook-setup" id="toc-notebook-setup" class="nav-link active" data-scroll-target="#notebook-setup"><span class="toc-section-number">3.1</span>  Notebook setup</a>
  <ul class="collapse">
  <li><a href="#clean-dataset" id="toc-clean-dataset" class="nav-link" data-scroll-target="#clean-dataset"><span class="toc-section-number">3.1.1</span>  Clean dataset</a></li>
  </ul></li>
  <li><a href="#area-plots" id="toc-area-plots" class="nav-link" data-scroll-target="#area-plots"><span class="toc-section-number">3.2</span>  Area plots</a>
  <ul class="collapse">
  <li><a href="#types-of-plotting" id="toc-types-of-plotting" class="nav-link" data-scroll-target="#types-of-plotting"><span class="toc-section-number">3.2.1</span>  Types of plotting</a></li>
  <li><a href="#two-types-of-plotting" id="toc-two-types-of-plotting" class="nav-link" data-scroll-target="#two-types-of-plotting"><span class="toc-section-number">3.2.2</span>  Two types of plotting</a></li>
  </ul></li>
  <li><a href="#histograms" id="toc-histograms" class="nav-link" data-scroll-target="#histograms"><span class="toc-section-number">3.3</span>  Histograms</a></li>
  <li><a href="#bar-charts" id="toc-bar-charts" class="nav-link" data-scroll-target="#bar-charts"><span class="toc-section-number">3.4</span>  Bar charts</a>
  <ul class="collapse">
  <li><a href="#vertical-bar-plot" id="toc-vertical-bar-plot" class="nav-link" data-scroll-target="#vertical-bar-plot"><span class="toc-section-number">3.4.1</span>  Vertical bar plot</a></li>
  <li><a href="#horizontal-barplots" id="toc-horizontal-barplots" class="nav-link" data-scroll-target="#horizontal-barplots"><span class="toc-section-number">3.4.2</span>  Horizontal barplots</a></li>
  </ul></li>
  <li><a href="#pie-charts" id="toc-pie-charts" class="nav-link" data-scroll-target="#pie-charts"><span class="toc-section-number">3.5</span>  Pie charts</a></li>
  <li><a href="#boxplots" id="toc-boxplots" class="nav-link" data-scroll-target="#boxplots"><span class="toc-section-number">3.6</span>  Boxplots</a></li>
  <li><a href="#scatter-plots" id="toc-scatter-plots" class="nav-link" data-scroll-target="#scatter-plots"><span class="toc-section-number">3.7</span>  Scatter plots</a></li>
  <li><a href="#bubble-plots" id="toc-bubble-plots" class="nav-link" data-scroll-target="#bubble-plots"><span class="toc-section-number">3.8</span>  Bubble Plots</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic visualization tools</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="notebook-setup" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="notebook-setup"><span class="header-section-number">3.1</span> Notebook setup</h2>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load libs</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib <span class="im">as</span> mpl</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#set graphics style</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>mpl.style.use(<span class="st">'ggplot'</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df_can <span class="op">=</span> pd.read_excel(<span class="st">"../data/Canada.xlsx"</span>, sheet_name<span class="op">=</span><span class="st">'Canada by Citizenship'</span>,skiprows<span class="op">=</span><span class="bu">range</span>(<span class="dv">20</span>), skipfooter<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#check data</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_can.head())</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_can.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Type    Coverage          OdName  AREA AreaName   REG  \
0  Immigrants  Foreigners     Afghanistan   935     Asia  5501   
1  Immigrants  Foreigners         Albania   908   Europe   925   
2  Immigrants  Foreigners         Algeria   903   Africa   912   
3  Immigrants  Foreigners  American Samoa   909  Oceania   957   
4  Immigrants  Foreigners         Andorra   908   Europe   925   

           RegName  DEV             DevName  1980  ...  2004  2005  2006  \
0    Southern Asia  902  Developing regions    16  ...  2978  3436  3009   
1  Southern Europe  901   Developed regions     1  ...  1450  1223   856   
2  Northern Africa  902  Developing regions    80  ...  3616  3626  4807   
3        Polynesia  902  Developing regions     0  ...     0     0     1   
4  Southern Europe  901   Developed regions     0  ...     0     0     1   

   2007  2008  2009  2010  2011  2012  2013  
0  2652  2111  1746  1758  2203  2635  2004  
1   702   560   716   561   539   620   603  
2  3623  4005  5393  4752  4325  3774  4331  
3     0     0     0     0     0     0     0  
4     1     0     0     0     0     1     1  

[5 rows x 43 columns]
(195, 43)</code></pre>
</div>
</div>
<section id="clean-dataset" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="clean-dataset"><span class="header-section-number">3.1.1</span> Clean dataset</h3>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#drop irrelevant columns</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df_can.drop([<span class="st">'AREA'</span>, <span class="st">'REG'</span>, <span class="st">'DEV'</span>, <span class="st">'Type'</span>, <span class="st">'Coverage'</span>], axis<span class="op">=</span><span class="dv">1</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#give some columns better names</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>df_can.rename(columns<span class="op">=</span>{<span class="st">'OdName'</span>:<span class="st">'Country'</span>, <span class="st">'AreaName'</span>:<span class="st">'Continent'</span>,<span class="st">'RegName'</span>:<span class="st">'Region'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># check whether all column have labels of type string.</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">all</span>(<span class="bu">isinstance</span>(column, <span class="bu">str</span>) <span class="cf">for</span> column <span class="kw">in</span> df_can.columns))</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">#change all columns to string type</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>df_can.columns <span class="op">=</span> <span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">str</span>, df_can.columns))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># let's check the column labels types now</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">all</span>(<span class="bu">isinstance</span>(column, <span class="bu">str</span>) <span class="cf">for</span> column <span class="kw">in</span> df_can.columns))</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the country name as index </span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>df_can.set_index(<span class="st">'Country'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co">#add a total column</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>df_can[<span class="st">'Total'</span>] <span class="op">=</span> df_can.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co">#create a list for the years of interest</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>years <span class="op">=</span> <span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">str</span>, <span class="bu">range</span>(<span class="dv">1980</span>, <span class="dv">2014</span>)))</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="co">#check df</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_can.head())</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'data dimensions:'</span>, df_can.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>False
True
               Continent           Region             DevName  1980  1981  \
Country                                                                     
Afghanistan         Asia    Southern Asia  Developing regions    16    39   
Albania           Europe  Southern Europe   Developed regions     1     0   
Algeria           Africa  Northern Africa  Developing regions    80    67   
American Samoa   Oceania        Polynesia  Developing regions     0     1   
Andorra           Europe  Southern Europe   Developed regions     0     0   

                1982  1983  1984  1985  1986  ...  2005  2006  2007  2008  \
Country                                       ...                           
Afghanistan       39    47    71   340   496  ...  3436  3009  2652  2111   
Albania            0     0     0     0     1  ...  1223   856   702   560   
Algeria           71    69    63    44    69  ...  3626  4807  3623  4005   
American Samoa     0     0     0     0     0  ...     0     1     0     0   
Andorra            0     0     0     0     2  ...     0     1     1     0   

                2009  2010  2011  2012  2013  Total  
Country                                              
Afghanistan     1746  1758  2203  2635  2004  58639  
Albania          716   561   539   620   603  15699  
Algeria         5393  4752  4325  3774  4331  69439  
American Samoa     0     0     0     0     0      6  
Andorra            0     0     0     1     1     15  

[5 rows x 38 columns]
data dimensions: (195, 38)</code></pre>
</div>
</div>
</section>
</section>
<section id="area-plots" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="area-plots"><span class="header-section-number">3.2</span> Area plots</h2>
<ul>
<li>also known as an area chart or graph is a type of plot</li>
<li>depicts cumulated totals using numbers or percentages over time</li>
<li>based on a line plot</li>
</ul>
<p>In the last module, we created a line plot that visualized the top 5 countries that contribued the most immigrants to Canada from 1980 to 2013. With a little modification to the code, we can visualize this plot as a cumulative plot, also knows as a Stacked Line Plot or Area plot.</p>
<p>Let’s first get the data for the top5 countries</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sort df</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df_can.sort_values([<span class="st">'Total'</span>], ascending <span class="op">=</span> <span class="va">False</span>, axis <span class="op">=</span> <span class="dv">0</span> , inplace <span class="op">=</span>  <span class="va">True</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#get the top5 countries</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>df_top5 <span class="op">=</span> df_can.head(<span class="dv">5</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co">#transpose data</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>df_top5 <span class="op">=</span> df_top5[years].transpose()</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co">#check data</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>df_top5.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th>Country</th>
      <th>India</th>
      <th>China</th>
      <th>United Kingdom of Great Britain and Northern Ireland</th>
      <th>Philippines</th>
      <th>Pakistan</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1980</th>
      <td>8880</td>
      <td>5123</td>
      <td>22045</td>
      <td>6051</td>
      <td>978</td>
    </tr>
    <tr>
      <th>1981</th>
      <td>8670</td>
      <td>6682</td>
      <td>24796</td>
      <td>5921</td>
      <td>972</td>
    </tr>
    <tr>
      <th>1982</th>
      <td>8147</td>
      <td>3308</td>
      <td>20620</td>
      <td>5249</td>
      <td>1201</td>
    </tr>
    <tr>
      <th>1983</th>
      <td>7338</td>
      <td>1863</td>
      <td>10015</td>
      <td>4562</td>
      <td>900</td>
    </tr>
    <tr>
      <th>1984</th>
      <td>5704</td>
      <td>1527</td>
      <td>10170</td>
      <td>3801</td>
      <td>668</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Area plots are stacked by default. And to produce a stacked area plot, each column must be either all positive or all negative values (any NaN, i.e.&nbsp;not a number, values will default to 0). To produce an unstacked plot, set parameter stacked to value False.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#change the index values to type integer</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#df_top5.index = df_top5.index.map(int)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#create area plot</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>df_top5.plot(kind <span class="op">=</span> <span class="st">'area'</span>, stacked <span class="op">=</span> <span class="va">False</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">4</span>))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#add labels</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Immigration trend in top5 countries'</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Years'</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-6-output-1.png" width="687" height="380"></p>
</div>
</div>
<p>The unstacked plot has a default transparency (alpha value) at 0.5. We can modify this value by passing in the alpha parameter.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create area plot</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df_top5.plot(kind <span class="op">=</span> <span class="st">'area'</span>, alpha <span class="op">=</span> <span class="fl">0.25</span>, stacked <span class="op">=</span> <span class="va">False</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">4</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#add labels</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Immigration trend in top5 countries'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Years'</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-7-output-1.png" width="687" height="380"></p>
</div>
</div>
<section id="types-of-plotting" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="types-of-plotting"><span class="header-section-number">3.2.1</span> Types of plotting</h3>
</section>
<section id="two-types-of-plotting" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="two-types-of-plotting"><span class="header-section-number">3.2.2</span> Two types of plotting</h3>
<section id="option-1-scripting-layer-procedural-method---using-matplotlib.pyplot-as-plt" class="level4" data-number="3.2.2.1">
<h4 data-number="3.2.2.1" class="anchored" data-anchor-id="option-1-scripting-layer-procedural-method---using-matplotlib.pyplot-as-plt"><span class="header-section-number">3.2.2.1</span> Option 1: Scripting layer (procedural method) - using matplotlib.pyplot as ‘plt’</h4>
<p>You can use <code>plt</code> i.e.&nbsp;<code>matplotlib.pyplot</code> and add more elements by calling different methods procedural; for example, <code>plt.title(...)</code> to add title or <code>plt.xlabel(...)</code> to add label to the x-axis.</p>
</section>
<section id="option-2-artist-layer-object-oriented-method---using-an-axes-instance-from-matplotlib-preferred" class="level4" data-number="3.2.2.2">
<h4 data-number="3.2.2.2" class="anchored" data-anchor-id="option-2-artist-layer-object-oriented-method---using-an-axes-instance-from-matplotlib-preferred"><span class="header-section-number">3.2.2.2</span> Option 2: Artist layer (Object oriented method) - using an <code>Axes</code> instance from Matplotlib (preferred)</h4>
<p>You can use an <code>Axes</code> instance of your current plot and store it in a variable (eg. <code>ax</code>). You can add more elements by calling methods with a little change in syntax (by adding “<code>set_</code>” to the previous methods). For example, use <code>ax.set_title()</code> instead of <code>plt.title()</code> to add title, or <code>ax.set_xlabel()</code> instead of <code>plt.xlabel()</code> to add label to the x-axis.</p>
<p>This option sometimes is more transparent and flexible to use for advanced plots (in particular when having multiple plots, as you will see later).</p>
<p>In this course, we will stick to the <strong>scripting layer</strong>, except for some advanced visualizations where we will need to use the <strong>artist layer</strong> to manipulate advanced aspects of the plots.</p>
<p>Let’s try an example for using the artist layer:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> df_top5.plot(kind <span class="op">=</span> <span class="st">'area'</span>, alpha <span class="op">=</span> <span class="fl">0.35</span>, figsize <span class="op">=</span> (<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Immigration Trend of Top 5 Countries'</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Years'</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-8-output-1.png" width="844" height="454"></p>
</div>
</div>
<p>Let’s Use the scripting layer to create a stacked area plot of the 5 countries that contributed the least to immigration to Canada from 1980 to 2013. Use a transparency value of 0.45.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#prep data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df_can_tail5 <span class="op">=</span> df_can.tail(<span class="dv">5</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df_can_tail5 <span class="op">=</span> df_can_tail5[years].transpose()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>df_can_tail5.plot(kind<span class="op">=</span><span class="st">'area'</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>             stacked<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>             figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))  <span class="co"># pass a tuple (x, y) size</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Immigration Trend of lowest 5 Countries'</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Years'</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-9-output-1.png" width="823" height="454"></p>
</div>
</div>
</section>
</section>
</section>
<section id="histograms" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="histograms"><span class="header-section-number">3.3</span> Histograms</h2>
<ul>
<li>A way of representing the frequency distribution of a numeric dataset</li>
<li>To do this numeric data is partitioned into into bins, each datapoint in the dataset is assigned to a bin, and then the number of datapoints that have been assigned to each bin are counted</li>
<li>The vertical axis is actually the frequency or the number of datapoints in each bin.</li>
</ul>
<p><strong>Question</strong>: What is the frequency distribution of the number (population) of new immigrants from the various countries to Canada in 2013?</p>
<p>Before we proceed with creating the histogram plot, let’s first examine the data split into intervals. To do this, we will us Numpy’s histrogram method to get the bin ranges and frequency counts as follows:</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>count, bin_edges <span class="op">=</span> np.histogram(df_can[<span class="st">'2013'</span>])</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">#print the frequency count and the bin ranges (by default 10 bins are used)</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(count)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bin_edges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[178  11   1   2   0   0   0   0   1   2]
[    0.   3412.9  6825.8 10238.7 13651.6 17064.5 20477.4 23890.3 27303.2
 30716.1 34129. ]</code></pre>
</div>
</div>
<p>By default, the histrogram method breaks up the dataset into 10 bins. The figure below summarizes the bin ranges and the frequency distribution of immigration in 2013. We can see that in 2013:</p>
<ul>
<li>178 countries contributed between 0 to 3412.9 immigrants</li>
<li>11 countries contributed between 3412.9 to 6825.8 immigrants</li>
<li>1 country contributed between 6285.8 to 10238.7 immigrants, and so on..</li>
</ul>
<p>We can easily graph this distribution by passing kind=hist to plot().</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df_can[<span class="st">'2013'</span>].plot(kind <span class="op">=</span> <span class="st">'hist'</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">5</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#add titles</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Histogram of Immigration from 195 countries in 2013"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Countries"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Immigrants"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-11-output-1.png" width="678" height="454"></p>
</div>
</div>
<p>In the above plot, the x-axis represents the population range of immigrants in intervals of 3412.9. The y-axis represents the number of countries that contributed to the aforementioned population.</p>
<p>Notice that the x-axis labels do not match with the bin size. This can be fixed by passing in a xticks keyword that contains the list of the bin sizes, as follows:</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#define the intervals</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>count, bin_edges <span class="op">=</span> np.histogram(df_can[<span class="st">'2013'</span>])</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>df_can[<span class="st">'2013'</span>].plot(kind <span class="op">=</span> <span class="st">'hist'</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">5</span>), xticks <span class="op">=</span> bin_edges)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co">#add titles</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Histogram of Immigration from 195 countries in 2013"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Countries"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Immigrants"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-12-output-1.png" width="670" height="454"></p>
</div>
</div>
<p>We can also plot multiple histograms on the same plot</p>
<p><strong>Question</strong>: What is the immigration distribution for Denmark, Norway, and Sweden for years 1980 - 2013?</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_can.loc[[<span class="st">'Denmark'</span>, <span class="st">'Norway'</span>, <span class="st">'Sweden'</span>], years].plot.hist()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-13-output-1.png" width="339" height="721"></p>
</div>
</div>
<p>That does not look right!</p>
<p>Don’t worry, you’ll often come across situations like this when creating plots. The solution often lies in how the underlying dataset is structured.</p>
<p>Instead of plotting the population frequency distribution of the population for the 3 countries, pandas instead plotted the population frequency distribution for the years.</p>
<p>This can be easily fixed by first transposing the dataset, and then plotting as shown below.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#transform data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>df_t <span class="op">=</span> df_can.loc[[<span class="st">'Denmark'</span>, <span class="st">'Norway'</span>, <span class="st">'Sweden'</span>], years].transpose()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>df_t.plot(kind<span class="op">=</span><span class="st">'hist'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Immigration from Denmark, Norway, and Sweden from 1980 - 2013'</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Years'</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-14-output-1.png" width="829" height="528"></p>
</div>
</div>
<p>Let’s make a few modifications to improve the impact and aesthetics of the previous plot:</p>
<ul>
<li>increase the bin size to 15 by passing in <code>bins</code> parameter;</li>
<li>set transparency to 60% by passing in <code>alpha</code> parameter;</li>
<li>label the x-axis by passing in <code>x-label</code> parameter;</li>
<li>change the colors of the plots by passing in <code>color</code> parameter.</li>
</ul>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get the tick values</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>count, bin_edges <span class="op">=</span> np.histogram(df_t, <span class="dv">15</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">#plot an unstacked histogram</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>df_t.plot(kind<span class="op">=</span><span class="st">'hist'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>), bins <span class="op">=</span> <span class="dv">15</span>, alpha <span class="op">=</span> <span class="fl">0.6</span>, xticks <span class="op">=</span> bin_edges,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>color <span class="op">=</span> [<span class="st">'coral'</span>, <span class="st">'darkslateblue'</span>, <span class="st">'mediumseagreen'</span>])</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Immigration from Denmark, Norway, and Sweden from 1980 - 2013'</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Years'</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-15-output-1.png" width="829" height="528"></p>
</div>
</div>
<p>For a full listing of colors available in Matplotlib, run the following code in your python shell:</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import matplotlib</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co">#for name, hex in matplotlib.colors.cnames.items():</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#    print(name, hex)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we do not want the plots to overlap each other, we can stack them using the stacked parameter. Let’s also adjust the min and max x-axis labels to remove the extra gap on the edges of the plot. We can pass a tuple (min,max) using the xlim paramater, as show below.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get the tick values</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>count, bin_edges <span class="op">=</span> np.histogram(df_t, <span class="dv">15</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  first bin value is 31.0, last is 308, adding buffer of 10 for aesthetic purposes</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>xmin <span class="op">=</span> bin_edges[<span class="dv">0</span>] <span class="op">-</span><span class="dv">10</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>xmax <span class="op">=</span> bin_edges[<span class="op">-</span><span class="dv">1</span>] <span class="op">+</span> <span class="dv">10</span> </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co">#plot a stacked histogram</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># stacked Histogram</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>df_t.plot(kind<span class="op">=</span><span class="st">'hist'</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>          figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>), </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>          bins<span class="op">=</span><span class="dv">15</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>          xticks<span class="op">=</span>bin_edges,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>          color<span class="op">=</span>[<span class="st">'coral'</span>, <span class="st">'darkslateblue'</span>, <span class="st">'mediumseagreen'</span>],</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>          stacked<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>          xlim<span class="op">=</span>(xmin, xmax)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Immigration from Denmark, Norway, and Sweden from 1980 - 2013'</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Years'</span>)</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-17-output-1.png" width="842" height="528"></p>
</div>
</div>
<p><strong>Question</strong>: Use the scripting layer to display the immigration distribution for Greece, Albania, and Bulgaria for years 1980 - 2013? Use an overlapping plot with 15 bins and a transparency value of 0.35.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#prep data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>df_2 <span class="op">=</span> df_can.loc[[<span class="st">'Greece'</span>, <span class="st">'Albania'</span>, <span class="st">'Bulgaria'</span>], years].transpose()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#set bins</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>count, bin_edges <span class="op">=</span> np.histogram(df_2, <span class="dv">15</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>df_2.plot(kind <span class="op">=</span> <span class="st">'hist'</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">6</span>), alpha <span class="op">=</span> <span class="fl">0.35</span>, xticks <span class="op">=</span> bin_edges, bins <span class="op">=</span> <span class="dv">15</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Immigration from Greece, Albania, and Bulgaria from 1980 - 2013'</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Years'</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-18-output-1.png" width="784" height="528"></p>
</div>
</div>
</section>
<section id="bar-charts" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="bar-charts"><span class="header-section-number">3.4</span> Bar charts</h2>
<ul>
<li>Used to compare the values of a variable at a given point in time</li>
</ul>
<p>To create a bar plot, we can pass one of two arguments via kind parameter in plot():</p>
<ul>
<li><code>kind=bar</code> creates a vertical bar plot</li>
<li><code>kind=barh</code> creates a horizontal bar plot</li>
</ul>
<section id="vertical-bar-plot" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="vertical-bar-plot"><span class="header-section-number">3.4.1</span> Vertical bar plot</h3>
<p>In vertical bar graphs, the x-axis is used for labelling, and the length of bars on the y-axis corresponds to the magnitude of the variable being measured. Vertical bar graphs are particularly useful in analyzing time series data. One disadvantage is that they lack space for text labelling at the foot of each bar.</p>
<p><strong>Let’s start off by analyzing the effect of Iceland’s Financial Crisis:</strong></p>
<p>The 2008 - 2011 Icelandic Financial Crisis was a major economic and political event in Iceland. Relative to the size of its economy, Iceland’s systemic banking collapse was the largest experienced by any country in economic history. The crisis led to a severe economic depression in 2008 - 2011 and significant political unrest.</p>
<p><strong>Question:</strong> Let’s compare the number of Icelandic immigrants (country = ‘Iceland’) to Canada from year 1980 to 2013.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#prep data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>df_iceland <span class="op">=</span> df_can.loc[<span class="st">'Iceland'</span>, years]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>df_iceland.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>1980    17
1981    33
1982    10
Name: Iceland, dtype: object</code></pre>
</div>
</div>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot the data</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>df_iceland.plot(kind <span class="op">=</span> <span class="st">'bar'</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">6</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>) <span class="co"># add to x-label to the plot</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of immigrants'</span>) <span class="co"># add y-label to the plot</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Icelandic immigrants to Canada from 1980 to 2013'</span>) <span class="co"># add title to the plot</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-20-output-1.png" width="662" height="549"></p>
</div>
</div>
<p>The bar plot above shows the total number of immigrants broken down by each year. We can clearly see the impact of the financial crisis; the number of immigrants to Canada started increasing rapidly after 2008.</p>
<p>Let’s annotate this on the plot using the <code>annotate</code> method of the <strong>scripting layer</strong> or the <strong>pyplot interface</strong>. We will pass in the following parameters:</p>
<ul>
<li><code>s</code>: str, the text of annotation.</li>
<li><code>xy</code>: Tuple specifying the (x,y) point to annotate (in this case, end point of arrow).</li>
<li><code>xytext</code>: Tuple specifying the (x,y) point to place the text (in this case, start point of arrow).</li>
<li><code>xycoords</code>: The coordinate system that xy is given in - ‘data’ uses the coordinate system of the object being annotated (default).</li>
<li><code>arrowprops</code>: Takes a dictionary of properties to draw the arrow:
<ul>
<li><code>arrowstyle</code>: Specifies the arrow style, <code>'-&gt;'</code> is standard arrow.</li>
<li><code>connectionstyle</code>: Specifies the connection type. <code>arc3</code> is a straight line.</li>
<li><code>color</code>: Specifies color of arrow.</li>
<li><code>lw</code>: Specifies the line width.</li>
</ul></li>
</ul>
<p>I encourage you to read the Matplotlib documentation for more details on annotations: <a href="http://matplotlib.orsg/api/pyplot_api.html#matplotlib.pyplot.annotate" class="uri">http://matplotlib.orsg/api/pyplot_api.html#matplotlib.pyplot.annotate</a>.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot the data and rotate xticks</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df_iceland.plot(kind <span class="op">=</span> <span class="st">'bar'</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">6</span>), rot <span class="op">=</span> <span class="dv">90</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>) <span class="co"># add to x-label to the plot</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of immigrants'</span>) <span class="co"># add y-label to the plot</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Icelandic immigrants to Canada from 1980 to 2013'</span>) <span class="co"># add title to the plot</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">#annotate arrow, h</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">''</span>, <span class="co"># s: str. Will leave it blank for no text</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(<span class="dv">32</span>,<span class="dv">70</span>), <span class="co"># place head of the arrow at point (year 2012 , pop 70)</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>            xytext<span class="op">=</span>(<span class="dv">28</span>,<span class="dv">20</span>), <span class="co"># place base of the arrow at point (year 2008 , pop 20)</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>            xycoords<span class="op">=</span><span class="st">'data'</span>, <span class="co"># will use the coordinate system of the object being annotated</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>            arrowprops <span class="op">=</span> <span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, connectionstyle<span class="op">=</span><span class="st">'arc3'</span>, color<span class="op">=</span><span class="st">'blue'</span>, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-21-output-1.png" width="662" height="549"></p>
</div>
</div>
<p>Let’s also annotate a text to go over the arrow. We will pass in the following additional parameters:</p>
<ul>
<li><code>rotation</code>: rotation angle of text in degrees (counter clockwise)</li>
<li><code>va</code>: vertical alignment of text [‘center’ | ‘top’ | ‘bottom’ | ‘baseline’]</li>
<li><code>ha</code>: horizontal alignment of text [‘center’ | ‘right’ | ‘left’]</li>
</ul>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot the data and rotate xticks</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df_iceland.plot(kind <span class="op">=</span> <span class="st">'bar'</span>, figsize <span class="op">=</span> (<span class="dv">8</span>,<span class="dv">6</span>), rot <span class="op">=</span> <span class="dv">90</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>) <span class="co"># add to x-label to the plot</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of immigrants'</span>) <span class="co"># add y-label to the plot</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Icelandic immigrants to Canada from 1980 to 2013'</span>) <span class="co"># add title to the plot</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co">#annotate arrow</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">''</span>, <span class="co"># s: str. Will leave it blank for no text</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(<span class="dv">32</span>,<span class="dv">70</span>), <span class="co"># place head of the arrow at point (year 2012 , pop 70)</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>            xytext<span class="op">=</span>(<span class="dv">28</span>,<span class="dv">20</span>), <span class="co"># place base of the arrow at point (year 2008 , pop 20)</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>            xycoords<span class="op">=</span><span class="st">'data'</span>, <span class="co"># will use the coordinate system of the object being annotated</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>            arrowprops <span class="op">=</span> <span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, connectionstyle<span class="op">=</span><span class="st">'arc3'</span>, color<span class="op">=</span><span class="st">'blue'</span>, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co">#annotate arrow</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">'2008-2011 Financal crisis'</span>,  <span class="co"># text to display</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(<span class="dv">28</span>,<span class="dv">30</span>),  <span class="co"># start the text at at point (year 2008 , pop 30)</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>            rotation<span class="op">=</span><span class="fl">73.5</span>, <span class="co"># based on trial and error to match the arrow</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>            va<span class="op">=</span><span class="st">'bottom'</span>, <span class="co"># want the text to be vertically 'bottom' aligned</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>            ha<span class="op">=</span><span class="st">'left'</span> <span class="co"># want the text to be horizontally 'left' aligned</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-22-output-1.png" width="662" height="549"></p>
</div>
</div>
</section>
<section id="horizontal-barplots" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="horizontal-barplots"><span class="header-section-number">3.4.2</span> Horizontal barplots</h3>
<p>Sometimes it is more practical to represent the data horizontally, especially if you need more room for labelling the bars. In horizontal bar graphs, the y-axis is used for labelling, and the length of bars on the x-axis corresponds to the magnitude of the variable being measured. As you will see, there is more room on the y-axis to label categorical variables.</p>
<p><strong>Question:</strong> Using the scripting later and the <code>df_can</code> dataset, create a <em>horizontal</em> bar plot showing the <em>total</em> number of immigrants to Canada from the top 15 countries, for the period 1980 - 2013. Label each country with the total immigrant count.</p>
<p>Step 1: Get the data pertaining to the top 15 countries.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df_top15 <span class="op">=</span> df_can[<span class="st">'Total'</span>].head(<span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Step 2: Plot data:</p>
<ol type="1">
<li>Use <code>kind='barh'</code> to generate a bar chart with horizontal bars.</li>
<li>Make sure to choose a good size for the plot and to label your axes and to give the plot a title.</li>
<li>Loop through the countries and annotate the immigrant population using the anotate function of the scripting interface.</li>
</ol>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df_top15.plot(kind<span class="op">=</span><span class="st">'barh'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.xlabel('Year')</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.ylabel('Number of Immigrants')</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Total number of Immigrants to Canada from 1980 to 2013</span><span class="ch">\n</span><span class="st"> in the Top15 countries'</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co">#annotate value labels for each country and add to plot</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, value <span class="kw">in</span> <span class="bu">enumerate</span>(df_top15):</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="bu">format</span>(value, <span class="st">','</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    plt.annotate(label, xy <span class="op">=</span> (value,  index <span class="op">-</span> <span class="fl">0.1</span>), color <span class="op">=</span> <span class="st">'black'</span>, size <span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-24-output-1.png" width="1158" height="528"></p>
</div>
</div>
</section>
</section>
<section id="pie-charts" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="pie-charts"><span class="header-section-number">3.5</span> Pie charts</h2>
<p>A <code>pie chart</code> is a circular graphic that displays numeric proportions by dividing a circle (or pie) into proportional slices. You are most likely already familiar with pie charts as it is widely used in business and media. We can create pie charts in Matplotlib by passing in the <code>kind=pie</code> keyword.</p>
<p>Let’s use a pie chart to explore the proportion (percentage) of new immigrants grouped by continents for the entire time period from 1980 to 2013.</p>
<p>Step 1: Gather data.</p>
<p>We will use <em>pandas</em> <code>groupby</code> method to summarize the immigration data by <code>Continent</code>. The general process of <code>groupby</code> involves the following steps:</p>
<ol type="1">
<li><strong>Split:</strong> Splitting the data into groups based on some criteria.</li>
<li><strong>Apply:</strong> Applying a function to each group independently: .sum() .count() .mean() .std() .aggregate() .apply() .etc..</li>
<li><strong>Combine:</strong> Combining the results into a data structure.</li>
</ol>
<p><img src="../images/Mod3Fig4SplitApplyCombine.png" width="400" align="center"></p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#group countries by continents and apply the sum function</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>df_continents <span class="op">=</span> df_can.groupby(<span class="st">'Continent'</span>, axis <span class="op">=</span> <span class="dv">0</span>).<span class="bu">sum</span>()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>df_continents.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>1980</th>
      <th>1981</th>
      <th>1982</th>
      <th>1983</th>
      <th>1984</th>
      <th>1985</th>
      <th>1986</th>
      <th>1987</th>
      <th>1988</th>
      <th>1989</th>
      <th>...</th>
      <th>2005</th>
      <th>2006</th>
      <th>2007</th>
      <th>2008</th>
      <th>2009</th>
      <th>2010</th>
      <th>2011</th>
      <th>2012</th>
      <th>2013</th>
      <th>Total</th>
    </tr>
    <tr>
      <th>Continent</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Africa</th>
      <td>3951</td>
      <td>4363</td>
      <td>3819</td>
      <td>2671</td>
      <td>2639</td>
      <td>2650</td>
      <td>3782</td>
      <td>7494</td>
      <td>7552</td>
      <td>9894</td>
      <td>...</td>
      <td>27523</td>
      <td>29188</td>
      <td>28284</td>
      <td>29890</td>
      <td>34534</td>
      <td>40892</td>
      <td>35441</td>
      <td>38083</td>
      <td>38543</td>
      <td>618948</td>
    </tr>
    <tr>
      <th>Asia</th>
      <td>31025</td>
      <td>34314</td>
      <td>30214</td>
      <td>24696</td>
      <td>27274</td>
      <td>23850</td>
      <td>28739</td>
      <td>43203</td>
      <td>47454</td>
      <td>60256</td>
      <td>...</td>
      <td>159253</td>
      <td>149054</td>
      <td>133459</td>
      <td>139894</td>
      <td>141434</td>
      <td>163845</td>
      <td>146894</td>
      <td>152218</td>
      <td>155075</td>
      <td>3317794</td>
    </tr>
    <tr>
      <th>Europe</th>
      <td>39760</td>
      <td>44802</td>
      <td>42720</td>
      <td>24638</td>
      <td>22287</td>
      <td>20844</td>
      <td>24370</td>
      <td>46698</td>
      <td>54726</td>
      <td>60893</td>
      <td>...</td>
      <td>35955</td>
      <td>33053</td>
      <td>33495</td>
      <td>34692</td>
      <td>35078</td>
      <td>33425</td>
      <td>26778</td>
      <td>29177</td>
      <td>28691</td>
      <td>1410947</td>
    </tr>
    <tr>
      <th>Latin America and the Caribbean</th>
      <td>13081</td>
      <td>15215</td>
      <td>16769</td>
      <td>15427</td>
      <td>13678</td>
      <td>15171</td>
      <td>21179</td>
      <td>28471</td>
      <td>21924</td>
      <td>25060</td>
      <td>...</td>
      <td>24747</td>
      <td>24676</td>
      <td>26011</td>
      <td>26547</td>
      <td>26867</td>
      <td>28818</td>
      <td>27856</td>
      <td>27173</td>
      <td>24950</td>
      <td>765148</td>
    </tr>
    <tr>
      <th>Northern America</th>
      <td>9378</td>
      <td>10030</td>
      <td>9074</td>
      <td>7100</td>
      <td>6661</td>
      <td>6543</td>
      <td>7074</td>
      <td>7705</td>
      <td>6469</td>
      <td>6790</td>
      <td>...</td>
      <td>8394</td>
      <td>9613</td>
      <td>9463</td>
      <td>10190</td>
      <td>8995</td>
      <td>8142</td>
      <td>7677</td>
      <td>7892</td>
      <td>8503</td>
      <td>241142</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 35 columns</p>
</div>
</div>
</div>
<p>Step 2: Plot the data. We will pass in <code>kind = 'pie'</code> keyword, along with the following additional parameters:</p>
<ul>
<li><code>autopct</code> - is a string or function used to label the wedges with their numeric value. The label will be placed inside the wedge. If it is a format string, the label will be <code>fmt%pct</code>.</li>
<li><code>startangle</code> - rotates the start of the pie chart by angle degrees counterclockwise from the x-axis.</li>
<li><code>shadow</code> - Draws a shadow beneath the pie (to give a 3D feel).</li>
</ul>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># autopct create %, start angle represent starting point</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>df_continents[<span class="st">'Total'</span>].plot(kind <span class="op">=</span> <span class="st">'pie'</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                            figsize <span class="op">=</span> (<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                            autopct<span class="op">=</span><span class="st">'</span><span class="sc">%1.1f%%</span><span class="st">'</span>, <span class="co">#add in percentages</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                            startangle<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                            shadow<span class="op">=</span><span class="va">True</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                            )</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Immigration to Canada by Continent [1980 - 2013]'</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'equal'</span>) <span class="co"># Sets the pie chart to look like a circle.</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-26-output-1.png" width="595" height="485"></p>
</div>
</div>
<p>The above visual is not very clear, the numbers and text overlap in some instances. Let’s make a few modifications to improve the visuals:</p>
<ul>
<li>Remove the text labels on the pie chart by passing in <code>legend</code> and add it as a seperate legend using <code>plt.legend()</code>.</li>
<li>Push out the percentages to sit just outside the pie chart by passing in <code>pctdistance</code> parameter.</li>
<li>Pass in a custom set of colors for continents by passing in <code>colors</code> parameter.</li>
<li><strong>Explode</strong> the pie chart to emphasize the lowest three continents (Africa, North America, and Latin America and Caribbean) by passing in <code>explode</code> parameter.</li>
</ul>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>colors_list <span class="op">=</span> [<span class="st">'gold'</span>, <span class="st">'yellowgreen'</span>, <span class="st">'lightcoral'</span>, <span class="st">'lightskyblue'</span>, <span class="st">'lightgreen'</span>, <span class="st">'pink'</span>]</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>explode_list <span class="op">=</span> [<span class="fl">0.1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>] <span class="co"># ratio for each continent with which to offset each wedge.</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>df_continents[<span class="st">'Total'</span>].plot(kind <span class="op">=</span> <span class="st">'pie'</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                            figsize <span class="op">=</span> (<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                            autopct<span class="op">=</span><span class="st">'</span><span class="sc">%1.1f%%</span><span class="st">'</span>, <span class="co">#add in percentages</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                            startangle<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                            shadow<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                            labels<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>                            pctdistance<span class="op">=</span><span class="fl">1.12</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>                            colors<span class="op">=</span>colors_list,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>                            explode<span class="op">=</span>explode_list</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>                            )</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co"># scale the title up by 12% to match pctdistance</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Immigration to Canada by Continent [1980 - 2013]'</span>, y<span class="op">=</span><span class="fl">1.12</span>) </span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">'equal'</span>) <span class="co"># Sets the pie chart to look like a circle.</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="co"># add legend</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>plt.legend(labels<span class="op">=</span>df_continents.index, loc<span class="op">=</span><span class="st">'upper left'</span>) </span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-27-output-1.png" width="508" height="538"></p>
</div>
</div>
<p>Question: Using a pie chart, explore the proportion (percentage) of new immigrants grouped by continents in the year 2013.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>explode_list <span class="op">=</span> [<span class="fl">0.0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.2</span>]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>df_continents[<span class="st">'2013'</span>].plot(kind<span class="op">=</span><span class="st">'pie'</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                            figsize <span class="op">=</span> (<span class="dv">6</span>,<span class="dv">5</span>),</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                            autopct<span class="op">=</span><span class="st">'</span><span class="sc">%1.1f%%</span><span class="st">'</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                            startangle<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                            shadow<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                            labels<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                            pctdistance<span class="op">=</span><span class="fl">1.12</span>, </span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>                            explode<span class="op">=</span>explode_list)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Immigration to canada in 2013"</span>, y <span class="op">=</span><span class="fl">1.12</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="co">#add legend</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>plt.legend(labels <span class="op">=</span> df_continents.index, loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-28-output-1.png" width="414" height="455"></p>
</div>
</div>
</section>
<section id="boxplots" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="boxplots"><span class="header-section-number">3.6</span> Boxplots</h2>
<p>So, what is a boxplot? A boxplot is a way of statistically representing the distribution of given data through 5 main dimensions.</p>
<ul>
<li>minimum, which is the smallest number in the sorted data. Its value can be obtained by subtracting 1.5 times the IQR where IQR is interquartile range from the first quartile.</li>
<li>first quartile which is 25% of the way through the sorted data. In other words, 1/4 of the data points are less than this value</li>
<li>median, which is the median of the sorted data</li>
<li>third quartile, which is 75% of the way through the sorted data. In other words, 3/4 of the data points are less than this value</li>
<li>maximum, which is the highest number in the sorted data where maximum equals third quartile summed with 1.5 multiplied by IQR</li>
<li>Boxplots also display outliers as individual dots that occur outside the upper and lower extremes</li>
</ul>
<p><img src="../images/boxplot_complete.png" width="440," align="center"></p>
<p>To make a <code>boxplot</code>, we can use <code>kind=box</code> in <code>plot</code> method invoked on a <em>pandas</em> series or dataframe.</p>
<p>Let’s plot the box plot for the Japanese immigrants between 1980 - 2013.</p>
<p>Step 1: Get the subset of the dataset. Even though we are extracting the data for just one country, we will obtain it as a dataframe. This will help us with calling the <code>dataframe.describe()</code> method to view the percentiles.</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#subset data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>df_japan <span class="op">=</span> df_can.loc[[<span class="st">'Japan'</span>], years].transpose()</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#ensure we have numericdata</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>df_japan.Japan <span class="op">=</span>df_japan.Japan.astype(<span class="bu">int</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>df_japan.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th>Country</th>
      <th>Japan</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1980</th>
      <td>701</td>
    </tr>
    <tr>
      <th>1981</th>
      <td>756</td>
    </tr>
    <tr>
      <th>1982</th>
      <td>598</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Step 2: Plot by passing in kind=‘box’.</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>df_japan.plot(kind<span class="op">=</span><span class="st">'box'</span>, figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span>))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Box plot of Japanese Immigrants from 1980 - 2013'</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-30-output-1.png" width="550" height="507"></p>
</div>
</div>
<p>We can immediately make a few key observations from the plot above:</p>
<ol type="1">
<li>The minimum number of immigrants is around 200 (min), maximum number is around 1300 (max), and median number of immigrants is around 900 (median).</li>
<li>25% of the years for period 1980 - 2013 had an annual immigrant count of ~500 or fewer (First quartile).</li>
<li>75% of the years for period 1980 - 2013 had an annual immigrant count of ~1100 or fewer (Third quartile).</li>
</ol>
<p>We can view the actual numbers by calling the <code>describe()</code> method on the dataframe.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df_japan.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th>Country</th>
      <th>Japan</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>34.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>814.911765</td>
    </tr>
    <tr>
      <th>std</th>
      <td>337.219771</td>
    </tr>
    <tr>
      <th>min</th>
      <td>198.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>529.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>902.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>1079.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>1284.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>One of the key benefits of box plots is comparing the distribution of multiple datasets. In one of the previous labs, we observed that China and India had very similar immigration trends. Let’s analyze these two countries further using box plots.</p>
<p><strong>Question:</strong> Compare the distribution of the number of new immigrants from India and China for the period 1980 - 2013.</p>
<p>Step 1: Get the dataset for China and India and call the dataframe df_CI.</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df_CI <span class="op">=</span> df_can.loc[[<span class="st">'China'</span>, <span class="st">'India'</span>], years].transpose()</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>df_CI.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th>Country</th>
      <th>China</th>
      <th>India</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1980</th>
      <td>5123</td>
      <td>8880</td>
    </tr>
    <tr>
      <th>1981</th>
      <td>6682</td>
      <td>8670</td>
    </tr>
    <tr>
      <th>1982</th>
      <td>3308</td>
      <td>8147</td>
    </tr>
    <tr>
      <th>1983</th>
      <td>1863</td>
      <td>7338</td>
    </tr>
    <tr>
      <th>1984</th>
      <td>1527</td>
      <td>5704</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Let’s view the percentiles associated with both countries using the describe() method.</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>df_CI.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th>Country</th>
      <th>China</th>
      <th>India</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>34.000000</td>
      <td>34.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>19410.647059</td>
      <td>20350.117647</td>
    </tr>
    <tr>
      <th>std</th>
      <td>13568.230790</td>
      <td>10007.342579</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1527.000000</td>
      <td>4211.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>5512.750000</td>
      <td>10637.750000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>19945.000000</td>
      <td>20235.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>31568.500000</td>
      <td>28699.500000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>42584.000000</td>
      <td>36210.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Step 2: Plot data.</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df_CI.plot(kind<span class="op">=</span><span class="st">'box'</span>, figsize <span class="op">=</span> (<span class="dv">6</span>,<span class="dv">6</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Box plot of Chinese and Indian Immigrants from 1980 - 2013'</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-34-output-1.png" width="607" height="507"></p>
</div>
</div>
<p>We can observe that, while both countries have around the same median immigrant population (~20,000), China’s immigrant population range is more spread out than India’s. The maximum population from India for any year (36,210) is around 15% lower than the maximum population from China (42,584).</p>
<p>If you prefer to create horizontal box plots, you can pass the vert parameter in the plot function and assign it to False. You can also specify a different color in case you are not a big fan of the default red color.</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>df_CI.plot(kind<span class="op">=</span><span class="st">'box'</span>, figsize <span class="op">=</span> (<span class="dv">6</span>,<span class="dv">6</span>), color <span class="op">=</span> <span class="st">'blue'</span>, vert <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Box plot of Chinese and Indian Immigrants from 1980 - 2013'</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-35-output-1.png" width="603" height="507"></p>
</div>
</div>
<p><strong>Subplots</strong></p>
<p>Often times we might want to plot multiple plots within the same figure. For example, we might want to perform a side by side comparison of the box plot with the line plot of China and India’s immigration.</p>
<p>To visualize multiple plots together, we can create a <strong><code>figure</code></strong> (overall canvas) and divide it into <strong><code>subplots</code></strong>, each containing a plot. With <strong>subplots</strong>, we usually work with the <strong>artist layer</strong> instead of the <strong>scripting layer</strong>.</p>
<p>Typical syntax is : <br></p>
<pre><code>    fig = plt.figure() # create figure
    ax = fig.add_subplot(nrows, ncols, plot_number) # create subplots</code></pre>
<p>Where</p>
<ul>
<li><code>nrows</code> and <code>ncols</code> are used to notionally split the figure into (<code>nrows</code> * <code>ncols</code>) sub-axes,</li>
<li><code>plot_number</code> is used to identify the particular subplot that this function is to create within the notional grid. <code>plot_number</code> starts at 1, increments across rows first and has a maximum of <code>nrows</code> * <code>ncols</code> as shown below.</li>
</ul>
<p><img src="../images/Mod3Fig5Subplots_V2.png" width="400" align="center"></p>
<p>We can then specify which subplot to place each plot by passing in the ax paramemter in plot() method as follows:</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure() <span class="co"># create figure</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>ax0 <span class="op">=</span> fig.add_subplot(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>) <span class="co"># add subplot 1 (2 row, 1 columns, first plot)</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> fig.add_subplot(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>) <span class="co"># add subplot 2 (2 row, 1 columns, second plot). See tip below**</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Subplot 1: Box plot</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>df_CI.plot(kind<span class="op">=</span><span class="st">'box'</span>, color<span class="op">=</span><span class="st">'blue'</span>, vert<span class="op">=</span><span class="va">False</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>), ax<span class="op">=</span>ax0) <span class="co"># add to subplot 1</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>ax0.set_title(<span class="st">'Box Plots of Immigrants from China and India (1980 - 2013)'</span>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>ax0.set_xlabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>ax0.set_ylabel(<span class="st">'Countries'</span>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Subplot 2: Line plot</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>df_CI.plot(kind<span class="op">=</span><span class="st">'line'</span>, figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">6</span>), ax<span class="op">=</span>ax1) <span class="co"># add to subplot 2</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>ax1.set_title (<span class="st">'Line Plots of Immigrants from China and India (1980 - 2013)'</span>)</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Years'</span>)</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-36-output-1.png" width="1580" height="528"></p>
</div>
</div>
<p><strong>Tip regarding subplot convention</strong></p>
<p>In the case when <code>nrows</code>, <code>ncols</code>, and <code>plot_number</code> are all less than 10, a convenience exists such that a 3-digit number can be given instead, where the hundreds represent <code>nrows</code>, the tens represent <code>ncols</code> and the units represent <code>plot_number</code>. For instance,</p>
<pre><code>   subplot(211) == subplot(2, 1, 1) </code></pre>
<p>produces a subaxes in a figure which represents the top plot (i.e.&nbsp;the first) in a 2 rows by 1 column notional grid (no grid actually exists, but conceptually this is how the returned subplot has been positioned).</p>
<p>Question: Create a box plot to visualize the distribution of the top 15 countries (based on total immigration) grouped by the decades 1980s, 1990s, and 2000s.</p>
<p>Step 1: Get the dataset. Get the top 15 countries based on Total immigrant population. Name the dataframe df_top15.</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>df_can.sort_values([<span class="st">'Total'</span>], ascending <span class="op">=</span> <span class="va">False</span>, axis <span class="op">=</span> <span class="dv">0</span> , inplace <span class="op">=</span>  <span class="va">True</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>df_top15 <span class="op">=</span> df_can.head(<span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Step 2: Create a new dataframe which contains the aggregate for each decade. One way to do that:</p>
<ol type="1">
<li>Create a list of all years in decades 80’s, 90’s, and 00’s.</li>
<li>Slice the original dataframe df_can to create a series for each decade and sum across all years for each country.</li>
<li>Merge the three series into a new data frame. Call your dataframe <strong>new_df</strong>.</li>
</ol>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a list of all years in decades 80's, 90's, and 00's</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>years_80s <span class="op">=</span> <span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">str</span>, <span class="bu">range</span>(<span class="dv">1980</span>, <span class="dv">1990</span>))) </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>years_90s <span class="op">=</span> <span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">str</span>, <span class="bu">range</span>(<span class="dv">1990</span>, <span class="dv">2000</span>))) </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>years_00s <span class="op">=</span> <span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">str</span>, <span class="bu">range</span>(<span class="dv">2000</span>, <span class="dv">2010</span>))) </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># slice the original dataframe df_can to create a series for each decade</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>df_80s <span class="op">=</span> df_top15.loc[:, years_80s].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>) </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>df_90s <span class="op">=</span> df_top15.loc[:, years_90s].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>) </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>df_00s <span class="op">=</span> df_top15.loc[:, years_00s].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="co"># merge the three series into a new data frame</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>new_df <span class="op">=</span> pd.DataFrame({<span class="st">'1980s'</span>: df_80s, <span class="st">'1990s'</span>: df_90s, <span class="st">'2000s'</span>:df_00s}) </span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="co"># display dataframe</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>new_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>1980s</th>
      <th>1990s</th>
      <th>2000s</th>
    </tr>
    <tr>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>India</th>
      <td>82154</td>
      <td>180395</td>
      <td>303591</td>
    </tr>
    <tr>
      <th>China</th>
      <td>32003</td>
      <td>161528</td>
      <td>340385</td>
    </tr>
    <tr>
      <th>United Kingdom of Great Britain and Northern Ireland</th>
      <td>179171</td>
      <td>261966</td>
      <td>83413</td>
    </tr>
    <tr>
      <th>Philippines</th>
      <td>60764</td>
      <td>138482</td>
      <td>172904</td>
    </tr>
    <tr>
      <th>Pakistan</th>
      <td>10591</td>
      <td>65302</td>
      <td>127598</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get basic stats</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>new_df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>1980s</th>
      <th>1990s</th>
      <th>2000s</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>15.000000</td>
      <td>15.000000</td>
      <td>15.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>44418.333333</td>
      <td>85594.666667</td>
      <td>97471.533333</td>
    </tr>
    <tr>
      <th>std</th>
      <td>44190.676455</td>
      <td>68237.560246</td>
      <td>100583.204205</td>
    </tr>
    <tr>
      <th>min</th>
      <td>7613.000000</td>
      <td>30028.000000</td>
      <td>13629.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>16698.000000</td>
      <td>39259.000000</td>
      <td>36101.500000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>30638.000000</td>
      <td>56915.000000</td>
      <td>65794.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>59183.000000</td>
      <td>104451.500000</td>
      <td>105505.500000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>179171.000000</td>
      <td>261966.000000</td>
      <td>340385.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Step 3: Plot the box plots.</p>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>new_df.plot(kind<span class="op">=</span><span class="st">'box'</span>, figsize <span class="op">=</span> (<span class="dv">6</span>,<span class="dv">6</span>), color <span class="op">=</span> <span class="st">'blue'</span>, vert <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Immigration from top 15 countries for decades 80s, 90s and 2000s'</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-40-output-1.png" width="664" height="507"></p>
</div>
</div>
<p>Note how the box plot differs from the summary table created. The box plot scans the data and identifies the outliers. In order to be an outlier, the data value must be:<br></p>
<ul>
<li>larger than Q3 by at least 1.5 times the interquartile range (IQR), or,</li>
<li>smaller than Q1 by at least 1.5 times the IQR.</li>
</ul>
<p>Let’s look at decade 2000s as an example: <br></p>
<ul>
<li>Q1 (25%) = 36,101.5 <br></li>
<li>Q3 (75%) = 105,505.5 <br></li>
<li>IQR = Q3 - Q1 = 69,404 <br></li>
</ul>
<p>Using the definition of outlier, any value that is greater than Q3 by 1.5 times IQR will be flagged as outlier.</p>
<p>Outlier &gt; 105,505.5 + (1.5 * 69,404) <br> Outlier &gt; 209,611.5</p>
</section>
<section id="scatter-plots" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="scatter-plots"><span class="header-section-number">3.7</span> Scatter plots</h2>
<ul>
<li>A scatter plot is a type of plot that displays values pertaining to typically two variables against each other.</li>
<li>Usually it is a dependent variable to be plotted against an independent variable in order to determine if any correlation between the two variables exists</li>
</ul>
<p>Let’s start by exploring the following:</p>
<p>Using a scatter plot, let’s visualize the trend of total immigrantion to Canada (all countries combined) for the years 1980 - 2013.</p>
<p>Step 1: Get the dataset. Since we are expecting to use the relationship betewen years and total population, we will convert years to int type.</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can use the sum() method to get the total population per year</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>df_tot <span class="op">=</span> pd.DataFrame(df_can[years].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># change the years to type int (useful for regression later on)</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>df_tot.index <span class="op">=</span> <span class="bu">map</span>(<span class="bu">int</span>, df_tot.index)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="co"># reset the index to put in back in as a column in the df_tot dataframe</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>df_tot.reset_index(inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="co"># rename columns</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>df_tot.columns <span class="op">=</span> [<span class="st">'year'</span>, <span class="st">'total'</span>]</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="co"># view the final dataframe</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>df_tot.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>year</th>
      <th>total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1980</td>
      <td>99137</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1981</td>
      <td>110563</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1982</td>
      <td>104271</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1983</td>
      <td>75550</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1984</td>
      <td>73417</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Step 2: Plot the data. In Matplotlib, we can create a scatter plot set by passing in kind=‘scatter’ as plot argument. We will also need to pass in x and y keywords to specify the columns that go on the x- and the y-axis.</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>df_tot.plot(kind<span class="op">=</span><span class="st">'scatter'</span>, x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'total'</span>, figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span>), color<span class="op">=</span><span class="st">'darkblue'</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Total Immigration to Canada from 1980 - 2013'</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-42-output-1.png" width="547" height="528"></p>
</div>
</div>
<p>Notice how the scatter plot does not connect the data points together. We can clearly observe an upward trend in the data: as the years go by, the total number of immigrants increases. We can mathematically analyze this upward trend using a regression line (line of best fit).</p>
<p>So let’s try to plot a linear line of best fit, and use it to predict the number of immigrants in 2015.</p>
<p>Step 1: Get the equation of line of best fit. We will use <strong>Numpy</strong>’s <code>polyfit()</code> method by passing in the following:</p>
<ul>
<li><code>x</code>: x-coordinates of the data.</li>
<li><code>y</code>: y-coordinates of the data.</li>
<li><code>deg</code>: Degree of fitting polynomial. 1 = linear, 2 = quadratic, and so on.</li>
</ul>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> df_tot[<span class="st">'year'</span>]</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_tot[<span class="st">'total'</span>]</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> np.polyfit(x,y, deg <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>array([ 5.56709228e+03, -1.09261952e+07])</code></pre>
</div>
</div>
<p>The output is an array with the polynomial coefficients, highest powers first. Since we are plotting a linear regression <code>y= a * x + b</code>, our output has 2 elements <code>[5.56709228e+03, -1.09261952e+07]</code> with the the slope in position 0 and intercept in position 1.</p>
<p>Step 2: Plot the regression line on the <code>scatter plot</code>.</p>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print out the line of best fit</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co">'No. Immigrants = {0:.0f} * Year + {1:.0f}'</span>.<span class="bu">format</span>(fit[<span class="dv">0</span>], fit[<span class="dv">1</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<pre><code>'No. Immigrants = 5567 * Year + -10926195'</code></pre>
</div>
</div>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>df_tot.plot(kind<span class="op">=</span><span class="st">'scatter'</span>, x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'total'</span>, figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span>), color<span class="op">=</span><span class="st">'darkblue'</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Total Immigration to Canada from 1980 - 2013'</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="co">#plot line of the best fit</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>plt.plot(x, fit[<span class="dv">0</span>] <span class="op">*</span> x <span class="op">+</span> fit[<span class="dv">1</span>], color<span class="op">=</span><span class="st">'red'</span>) <span class="co"># recall that x is the Years</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">'y=</span><span class="sc">{0:.0f}</span><span class="st"> x + </span><span class="sc">{1:.0f}</span><span class="st">'</span>.<span class="bu">format</span>(fit[<span class="dv">0</span>], fit[<span class="dv">1</span>]), xy<span class="op">=</span>(<span class="dv">2000</span>, <span class="dv">150000</span>))</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-45-output-1.png" width="547" height="528"></p>
</div>
</div>
<p>Using the equation of line of best fit, we can estimate the number of immigrants in 2015:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>No. Immigrants <span class="op">=</span> <span class="dv">5567</span> <span class="op">*</span> Year <span class="op">-</span> <span class="dv">10926195</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>No. Immigrants <span class="op">=</span> <span class="dv">5567</span> <span class="op">*</span> <span class="dv">2015</span> <span class="op">-</span> <span class="dv">10926195</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>No. Immigrants <span class="op">=</span> <span class="dv">291</span>,<span class="dv">310</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>When compared to the actual from Citizenship and Immigration Canada’s (CIC) <a href="http://www.cic.gc.ca/english/resources/publications/annual-report-2016/index.asp?utm_medium=Exinfluencer&amp;utm_source=Exinfluencer&amp;utm_content=000026UJ&amp;utm_term=10006555&amp;utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDV0101ENSkillsNetwork20297740-2022-01-01">2016 Annual Report</a>, we see that Canada accepted 271,845 immigrants in 2015. Our estimated value of 291,310 is within 7% of the actual number, which is pretty good considering our original data came from United Nations (and might differ slightly from CIC data).</p>
<p>As a side note, we can observe that immigration took a dip around 1993 - 1997. Further analysis into the topic revealed that in 1993 Canada introcuded Bill C-86 which introduced revisions to the refugee determination system, mostly restrictive. Further amendments to the Immigration Regulations cancelled the sponsorship required for “assisted relatives” and reduced the points awarded to them, making it more difficult for family members (other than nuclear family) to immigrate to Canada. These restrictive measures had a direct impact on the immigration numbers for the next several years.</p>
<p>Question: Create a scatter plot of the total immigration from Denmark, Norway, and Sweden to Canada from 1980 to 2013?</p>
<p><strong>Step 1</strong>: Get the data:</p>
<ol type="1">
<li>Create a dataframe the consists of the numbers associated with Denmark, Norway, and Sweden only. Name it <strong>df_countries</strong>.</li>
<li>Sum the immigration numbers across all three countries for each year and turn the result into a dataframe. Name this new dataframe <strong>df_total</strong>.</li>
<li>Reset the index in place.</li>
<li>Rename the columns to <strong>year</strong> and <strong>total</strong>.</li>
<li>Display the resulting dataframe.</li>
</ol>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#subset data</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>df_countries <span class="op">=</span> df_can.loc[[<span class="st">'Denmark'</span>, <span class="st">'Norway'</span>, <span class="st">'Sweden'</span>], years]</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co">#get total</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>df_total <span class="op">=</span> pd.DataFrame(df_can[years].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co">#reset index</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>df_total.reset_index(inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="co">#rename columns</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>df_total.columns <span class="op">=</span> [<span class="st">'year'</span>, <span class="st">'total'</span>]</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="co"># change column year from string to int to create scatter plot</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>df_total[<span class="st">'year'</span>] <span class="op">=</span> df_total[<span class="st">'year'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>df_total.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>year</th>
      <th>total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1980</td>
      <td>99137</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1981</td>
      <td>110563</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1982</td>
      <td>104271</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Step 2: Generate the scatter plot by plotting the total versus year in df_total.</p>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>df_total.plot(kind<span class="op">=</span><span class="st">'scatter'</span>, x<span class="op">=</span><span class="st">'year'</span>, y<span class="op">=</span><span class="st">'total'</span>, figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span>), color<span class="op">=</span><span class="st">'darkblue'</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Total Immigration from Denmark, Norway and Sweden to Canada from 1980 - 2013'</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-47-output-1.png" width="820" height="528"></p>
</div>
</div>
</section>
<section id="bubble-plots" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="bubble-plots"><span class="header-section-number">3.8</span> Bubble Plots</h2>
<p>A <code>bubble plot</code> is a variation of the <code>scatter plot</code> that displays three dimensions of data (x, y, z). The data points are replaced with bubbles, and the size of the bubble is determined by the third variable <code>z</code>, also known as the weight. In <code>maplotlib</code>, we can pass in an array or scalar to the parameter <code>s</code> to <code>plot()</code>, that contains the weight of each point.</p>
<p><strong>Let’s start by analyzing the effect of Argentina’s great depression</strong>.</p>
<p>Argentina suffered a great depression from 1998 to 2002, which caused widespread unemployment, riots, the fall of the government, and a default on the country’s foreign debt. In terms of income, over 50% of Argentines were poor, and seven out of ten Argentine children were poor at the depth of the crisis in 2002.</p>
<p>Let’s analyze the effect of this crisis, and compare Argentina’s immigration to that of it’s neighbour Brazil. Let’s do that using a <code>bubble plot</code> of immigration from Brazil and Argentina for the years 1980 - 2013. We will set the weights for the bubble as the <em>normalized</em> value of the population for each year.</p>
<p>Step 1: Get the data for Brazil and Argentina. Like in the previous example, we will convert the Years to type int and include it in the dataframe.</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># transposed dataframe</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>df_can_t <span class="op">=</span> df_can[years].transpose()</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># cast the Years (the index) to type int</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>df_can_t.index <span class="op">=</span> <span class="bu">map</span>(<span class="bu">int</span>, df_can_t.index)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co"># let's label the index. This will automatically be the column name when we reset the index</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>df_can_t.index.name <span class="op">=</span> <span class="st">'Year'</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co"># reset index to bring the Year in as a column</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>df_can_t.reset_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="co"># view the changes</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>df_can_t.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th>Country</th>
      <th>Year</th>
      <th>India</th>
      <th>China</th>
      <th>United Kingdom of Great Britain and Northern Ireland</th>
      <th>Philippines</th>
      <th>Pakistan</th>
      <th>United States of America</th>
      <th>Iran (Islamic Republic of)</th>
      <th>Sri Lanka</th>
      <th>Republic of Korea</th>
      <th>...</th>
      <th>Kiribati</th>
      <th>Vanuatu</th>
      <th>Sao Tome and Principe</th>
      <th>Tuvalu</th>
      <th>American Samoa</th>
      <th>San Marino</th>
      <th>New Caledonia</th>
      <th>Marshall Islands</th>
      <th>Western Sahara</th>
      <th>Palau</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1980</td>
      <td>8880</td>
      <td>5123</td>
      <td>22045</td>
      <td>6051</td>
      <td>978</td>
      <td>9378</td>
      <td>1172</td>
      <td>185</td>
      <td>1011</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1981</td>
      <td>8670</td>
      <td>6682</td>
      <td>24796</td>
      <td>5921</td>
      <td>972</td>
      <td>10030</td>
      <td>1429</td>
      <td>371</td>
      <td>1456</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1982</td>
      <td>8147</td>
      <td>3308</td>
      <td>20620</td>
      <td>5249</td>
      <td>1201</td>
      <td>9074</td>
      <td>1822</td>
      <td>290</td>
      <td>1572</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1983</td>
      <td>7338</td>
      <td>1863</td>
      <td>10015</td>
      <td>4562</td>
      <td>900</td>
      <td>7100</td>
      <td>1592</td>
      <td>197</td>
      <td>1081</td>
      <td>...</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1984</td>
      <td>5704</td>
      <td>1527</td>
      <td>10170</td>
      <td>3801</td>
      <td>668</td>
      <td>6661</td>
      <td>1977</td>
      <td>1086</td>
      <td>847</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 196 columns</p>
</div>
</div>
</div>
<p><strong>Step 2</strong>: Create the normalized weights.</p>
<p>There are several methods of normalizations in statistics, each with its own use. In this case, we will use <a href="https://en.wikipedia.org/wiki/Feature_scaling?utm_medium=Exinfluencer&amp;utm_source=Exinfluencer&amp;utm_content=000026UJ&amp;utm_term=10006555&amp;utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDV0101ENSkillsNetwork20297740-2022-01-01">feature scaling</a> to bring all values into the range. The general formula is:</p>
<p><img src="../images/Mod3Fig3FeatureScaling.png" align="center"></p>
<p>where <span class="math inline">\(X\)</span> is the original value, <span class="math inline">\(X'\)</span> is the corresponding normalized value. The formula sets the max value in the dataset to 1, and sets the min value to 0. The rest of the data points are scaled to a value between 0-1 accordingly.</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># normalize Brazil data</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>norm_brazil <span class="op">=</span> (df_can_t[<span class="st">'Brazil'</span>] <span class="op">-</span> df_can_t[<span class="st">'Brazil'</span>].<span class="bu">min</span>()) <span class="op">/</span> (df_can_t[<span class="st">'Brazil'</span>].<span class="bu">max</span>() <span class="op">-</span> df_can_t[<span class="st">'Brazil'</span>].<span class="bu">min</span>())</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># normalize Argentina data</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>norm_argentina <span class="op">=</span> (df_can_t[<span class="st">'Argentina'</span>] <span class="op">-</span> df_can_t[<span class="st">'Argentina'</span>].<span class="bu">min</span>()) <span class="op">/</span> (df_can_t[<span class="st">'Argentina'</span>].<span class="bu">max</span>() <span class="op">-</span> df_can_t[<span class="st">'Argentina'</span>].<span class="bu">min</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Step 3</strong>: Plot the data.</p>
<ul>
<li>To plot two different scatter plots in one plot, we can include the axes one plot into the other by passing it via the <code>ax</code> parameter.</li>
<li>We will also pass in the weights using the <code>s</code> parameter. Given that the normalized weights are between 0-1, they won’t be visible on the plot. Therefore, we will:
<ul>
<li>multiply weights by 2000 to scale it up on the graph, and,</li>
<li>add 10 to compensate for the min value (which has a 0 weight and therefore scale with <span class="math inline">\(\times 2000\)</span>).</li>
</ul></li>
</ul>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Brazil</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>ax0 <span class="op">=</span> df_can_t.plot(kind<span class="op">=</span><span class="st">'scatter'</span>,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>                    x<span class="op">=</span><span class="st">'Year'</span>,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>                    y<span class="op">=</span><span class="st">'Brazil'</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>                    figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>),</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>                    alpha<span class="op">=</span><span class="fl">0.5</span>,  <span class="co"># transparency</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>                    color<span class="op">=</span><span class="st">'green'</span>,</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>                    s<span class="op">=</span>norm_brazil <span class="op">*</span> <span class="dv">2000</span> <span class="op">+</span> <span class="dv">10</span>,  <span class="co"># pass in weights </span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>                    xlim<span class="op">=</span>(<span class="dv">1975</span>, <span class="dv">2015</span>)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Argentina</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> df_can_t.plot(kind<span class="op">=</span><span class="st">'scatter'</span>,</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>                    x<span class="op">=</span><span class="st">'Year'</span>,</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>                    y<span class="op">=</span><span class="st">'Argentina'</span>,</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>                    alpha<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>                    color<span class="op">=</span><span class="st">"blue"</span>,</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>                    s<span class="op">=</span>norm_argentina <span class="op">*</span> <span class="dv">2000</span> <span class="op">+</span> <span class="dv">10</span>,</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>                    ax<span class="op">=</span>ax0</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>ax0.set_ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>ax0.set_title(<span class="st">'Immigration from Brazil and Argentina from 1980 to 2013'</span>)</span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>ax0.legend([<span class="st">'Brazil'</span>, <span class="st">'Argentina'</span>], loc<span class="op">=</span><span class="st">'upper left'</span>, fontsize<span class="op">=</span><span class="st">'x-large'</span>)</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-50-output-1.png" width="695" height="528"></p>
</div>
</div>
<p>The size of the bubble corresponds to the magnitude of immigrating population for that year, compared to the 1980 - 2013 data. The larger the bubble is, the more immigrants are in that year.</p>
<p>From the plot above, we can see a corresponding increase in immigration from Argentina during the 1998 - 2002 great depression. We can also observe a similar spike around 1985 to 1993. In fact, Argentina had suffered a great depression from 1974 to 1990, just before the onset of 1998 - 2002 great depression.</p>
<p>On a similar note, Brazil suffered the <em>Samba Effect</em> where the Brazilian real (currency) dropped nearly 35% in 1999. There was a fear of a South American financial crisis as many South American countries were heavily dependent on industrial exports from Brazil. The Brazilian government subsequently adopted an austerity program, and the economy slowly recovered over the years, culminating in a surge in 2010. The immigration data reflect these events.</p>
<p><strong>Question</strong>: Previously in this lab, we created box plots to compare immigration from China and India to Canada. Create bubble plots of immigration from China and India to visualize any differences with time from 1980 to 2013. You can use <strong>df_can_t</strong> that we defined and used in the previous example.</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># normalized Chinese data</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>norm_china <span class="op">=</span> (df_can_t[<span class="st">'China'</span>] <span class="op">-</span> df_can_t[<span class="st">'China'</span>].<span class="bu">min</span>()) <span class="op">/</span> (df_can_t[<span class="st">'China'</span>].<span class="bu">max</span>() <span class="op">-</span> df_can_t[<span class="st">'China'</span>].<span class="bu">min</span>())</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># normalized Indian data</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>norm_india <span class="op">=</span> (df_can_t[<span class="st">'India'</span>] <span class="op">-</span> df_can_t[<span class="st">'India'</span>].<span class="bu">min</span>()) <span class="op">/</span> (df_can_t[<span class="st">'India'</span>].<span class="bu">max</span>() <span class="op">-</span> df_can_t[<span class="st">'India'</span>].<span class="bu">min</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>ax0 <span class="op">=</span> df_can_t.plot(kind<span class="op">=</span><span class="st">'scatter'</span>,</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                        x<span class="op">=</span><span class="st">'Year'</span>,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                        y<span class="op">=</span><span class="st">'China'</span>,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>                        figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">8</span>),</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>                        alpha<span class="op">=</span><span class="fl">0.5</span>,                  <span class="co"># transparency</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>                        color<span class="op">=</span><span class="st">'green'</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>                        s<span class="op">=</span>norm_china <span class="op">*</span> <span class="dv">2000</span> <span class="op">+</span> <span class="dv">10</span>,  <span class="co"># pass in weights </span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>                        xlim<span class="op">=</span>(<span class="dv">1975</span>, <span class="dv">2015</span>)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="co"># India</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> df_can_t.plot(kind<span class="op">=</span><span class="st">'scatter'</span>,</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>                        x<span class="op">=</span><span class="st">'Year'</span>,</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>                        y<span class="op">=</span><span class="st">'India'</span>,</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>                        alpha<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>                        color<span class="op">=</span><span class="st">"blue"</span>,</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>                        s<span class="op">=</span>norm_india <span class="op">*</span> <span class="dv">2000</span> <span class="op">+</span> <span class="dv">10</span>,</span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>                        ax <span class="op">=</span> ax0</span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>ax0.set_ylabel(<span class="st">'Number of Immigrants'</span>)</span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>ax0.set_title(<span class="st">'Immigration from China and India from 1980 - 2013'</span>)</span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a>ax0.legend([<span class="st">'China'</span>, <span class="st">'India'</span>], loc<span class="op">=</span><span class="st">'upper left'</span>, fontsize<span class="op">=</span><span class="st">'x-large'</span>)</span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb60-26"><a href="#cb60-26" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2_basic_vis_tools_files/figure-html/cell-52-output-1.png" width="1150" height="676"></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../code/1_intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction into data vis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../code/3_advanced_vis_tools.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Advanced visualization tools</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>