# Extracting Stock Data Using a Python Library

A company's stock share is a piece of the company more precisely:

A stock (also known as equity) is a security that represents the ownership of a fraction of a corporation. This entitles the owner of the stock to a proportion of the corporation's assets and profits equal to how much stock they own. Units of stock are called "shares." [1]

An investor can buy a stock and sell it later. If the stock price increases, the investor profits, If it decreases,the investor with incur a loss.  Determining the stock price is complex; it depends on the number of outstanding shares, the size of the company's future profits, and much more. People trade stocks throughout the day the stock ticker is a report of the price of a certain stock, updated continuously throughout the trading session by the various stock market exchanges.

You are a data scientist working for a hedge fund; it's your job to determine any suspicious stock activity. In this lab you will extract stock data using a Python library. We will use the **yfinance** library, it allows us to extract data for stocks returning data in a pandas dataframe. You will use the lab to extract.

## Loading required libraries

```{python}
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
```


## Using the yfinance Library to Extract Stock Data

Using the Ticker module we can create an object that will allow us to access functions to extract data. To do this we need to provide the ticker symbol for the stock, here the company is Apple and the ticker symbol is AAPL.

```{python}
apple = yf.Ticker("AAPL")
```

Now we can access functions and variables to extract the type of data we need. You can view them and what they represent here https://aroussi.com/post/python-yahoo-finance.


## Stock info

Using the attribute info we can extract information about the stock as a Python dictionary.

```{python}
apple_info = apple.info
apple_info
```

We can get the 'country' using the key country

```{python}
print(type(apple))
print(type(apple_info))

print(apple_info['country'])
```


## Extracting Share Price

A **share** is the single smallest part of a company's stock that you can buy, the prices of these shares fluctuate over time. Using the **history() method** we can get the share price of the stock over a certain period of time. Using the period parameter we can set how far back from the present to get data. The options for period are 1 day (1d), 5d, 1 month (1mo) , 3mo, 6mo, 1 year (1y), 2y, 5y, 10y, ytd, and max.

The format that the data is returned in is a Pandas DataFrame. With the Date as the index the share Open, High, Low, Close, Volume, and Stock Splits are given for each day.

```{python}
apple_share_price_data = apple.history(period = "max")
apple_share_price_data.head()
```
We can reset the index of the DataFrame with the `reset_index` function. We also set the `inplace` paramter to True so the change takes place to the DataFrame itself.

```{python}
apple_share_price_data.reset_index(inplace = True)
apple_share_price_data.head()
```

We can plot the Open price against the Date:

```{python}
apple_share_price_data.plot(x='Date', y = 'Open')
plt.show()
```

## Extracting Dividends

**Dividends** are the distribution of a companys profits to shareholders. In this case they are defined as an amount of money returned per share an investor owns. Using the variable `dividends` we can get a dataframe of the data. The period of the data is given by the period defined in the 'history` function.

```{python}
apple.dividends.head()
```

We can plot the dividens over time

```{python}
apple.dividends.plot()
plt.show()
```

## Exercise

Now using the Ticker module create an object for AMD (Advanced Micro Devices) with the ticker symbol is AMD called; name the object amd.

```{python}
amd = yf.Ticker("AMD")
type(amd)
```

- Use the key 'country' to find the country the stock belongs to, remember it as it will be a quiz question.

```{python}
amd_info = amd.info
amd_info['country']
```

- Use the key 'sector' to find the sector the stock belongs to, remember it as it will be a quiz question.

```{python}
amd_info['sector']
```

- Obtain stock data for AMD using the history function, set the period to max. Find the Volume traded on the first day (first row).

```{python}
amd_stock_data = amd.history(period="max").reset_index()
print(amd_stock_data.head())
print(amd_stock_data.loc[0, 'Volume'])
```


